import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="max-h-screen h-screen">
        {children}
        <footer className="text-neutral-400 text-center p-4 text-sm">
          Copyright © 2023 microncn
        </footer>
      </body>
    </html>
  );
}
