import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
});

import flag from "../images/palestine.png";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="max-h-screen h-screen">
        <a
          href="https://www.launchgood.com/communitypage/support_palestinians_in_gaza"
          target="_blank"
          className="flex justify-center items-center bg-neutral-800 text-white py-2 gap-2"
        >
          <img src={flag.src} className="w-5" />
          <p>#FreePalestine</p>
        </a>
        {children}
        <footer className="text-neutral-400 text-center p-4 text-sm">
          Copyright © 2023 microncn
        </footer>
      </body>
    </html>
  );
}
